name: push

on:
  workflow_dispatch:

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: Checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@db6b3c02208c08f0d449436304888e454c3aca20
        with:
          quiet: false
          soft_fail: false
          framework: terraform
          output_format: cli
